version: '3'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        container_name: elasticsearch
        environment:
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
            - discovery.type=single-node
            - http.cors.enabled=true
            - http.cors.allow-origin=*
        ports:
            - '9200:9200'
        restart: always
        networks:
            - serasatest

    webapp:
        container_name: orderapp
        build:
          context: .
          dockerfile: Dockerfile
        environment: 
            port: 8081
        ports:
            - '8081:8081'
        depends_on: 
            - elasticsearch
        links: 
            - elasticsearch
        networks:
            - serasatest
        expose:
            - 8081
        restart: always

networks:
    serasatest:
        name: serasatest